# Generated by Django 4.2.2 on 2023-06-20 10:15

from django.db import migrations, models
import uuid


class Migration(migrations.Migration):
    dependencies = [
        ("apis", "0001_initial"),
    ]

    operations = [
        migrations.CreateModel(
            name="TaskModel",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                ("title", models.CharField(max_length=255, unique=True)),
                ("content", models.TextField()),
                ("createdAt", models.DateTimeField(auto_now_add=True)),
                ("updatedAt", models.DateTimeField(auto_now_add=True)),
            ],
            options={
                "db_table": "tasks",
                "ordering": ["createdAt"],
            },
        ),
        migrations.DeleteModel(
            name="Task",
        ),
        migrations.AddConstraint(
            model_name="taskmodel",
            constraint=models.UniqueConstraint(fields=("title",), name="unique_title"),
        ),
    ]
